AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Miner Configuration
        Parameters:
          - Miner
          - EthWallet
          - Url1
          - Url2
          - Worker
          - Password

      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceType
          - InstanceAmi

      - Label:
          default: Networking Configuration
        Parameters:
          - VpcId
          - SubnetIds
          - SSHAccessIP
          - ChooseVPC
          - KeyName

    ParameterLabels:
      KeyName:
        default: EC2 Key Pair
      SSHAccessIP:
        default: Restrict SSH To

Parameters:
  KeyName:
    Description: REQUIRED - Select an EXISTING EC2 key pair to launch your Siacoin miner instances.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: You must choose the name of an existing EC2 KeyPair
    Default: brad-template
  SSHAccessIP:
    Description: Enter your source IP for SSH access. Use http://ipchicken.com if not sure. Note that 0.0.0.0/0 isn't allowed to protect yourself from yourself.
    Type: String
    MinLength: 9
    MaxLength: 18
    Default : 98.202.252.84/32
    AllowedValues:
      - 0.0.0.0/0
      - 98.202.252.84/32
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})(/32)"
    ConstraintDescription: Must be a valid CIDR range of the form x.x.x.x/32
  InstanceType:
    Type: String
    Default: g4dn.xlarge
    AllowedValues:
      # Amazon Linux 2 AMI with NVIDIA TESLA GPU Driver
      ## The commented-out are not worth it - too slow for the price
      #- g3s.xlarge    # 1 GPU Tesla M60
      #- g3.8xlarge    # 2 GPU Tesla M60
      - g4dn.xlarge   # 1 GPU Tesla T4 -- best value (cost/performance)
      - g4dn.2xlarge  # 1 GPU Tesla T4
      - g4dn.12xlarge # 4 GPU Tesla T4
      - g4dn.metal
      #- p2.xlarge     # 1 GPU Tesla K80
      #- p2.8xlarge    # 8 GPU Tesla K80
      #- p2.16xlarge   # 16 GPU Tesla K80
      - p3.2xlarge    # 1 GPU Tesla V100
      - p3.8xlarge    # 4 GPU Tesla V100
      - p3.16xlarge   # 8 GPU Tesla V100

  InstanceCount:
    Type: Number
    Default: 5
    MaxValue: 10

  EthWallet:
    Type: String
    Description: Ethereum Wallet Address
    Default: "0x36568B6348f1d5256Fed5E0a007AEA7541f6d618"
    AllowedPattern: "0x[0-9a-fA-F]+"

  Miner:
    Type: String
    Description: What kind of miner
    Default: twominerseth
    AllowedValues:
      - betterhasheth
      - twominersravencoin
      - twominerseth
      - ethermineeth

  Url1:
    Type: String
    Description: Pool Url 1
    Default: "88.198.11.177:55439"

  Url2:
    Type: String
    Description: Pool Url 2
    Default: "38.91.101.106:55439"

  Worker:
    Type: String
    Description: Worker
    Default: "xxxWALLETxxx.0000FCB0"

  Password:
    Type: String
    Description: Password
    Default: "xxxPASSxxx"

  VpcId:
    Description: The VPC where this stack will be deployed
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Description: The subnets where the instances will be deployed - at least 3 subnets!
    Type: List<AWS::EC2::Subnet::Id>

Mappings:
  # ImageId of 'Deep Learning AMI (Ubuntu 18.04) Version 36.0' in each region
  RegionMap:
    ap-northeast-1:
      ImageId: ami-03b8cfea5460e4881
    ap-northeast-2:
      ImageId: ami-07e004f63a0cccdd3
    ap-south-1:
      ImageId: ami-02cb047909c100c3d
    ap-southeast-1:
      ImageId: ami-068f673b54015684e
    ap-southeast-2:
      ImageId: ami-0f558ede443627831
    ca-central-1:
      ImageId: ami-0ca5bba27cf7db8f0
    eu-central-1:
      ImageId: ami-01227276a4e5a4a31
    eu-north-1:
      ImageId: ami-080691999cd85e762
    eu-west-1:
      ImageId: ami-006ff58f5247c50eb
    eu-west-2:
      ImageId: ami-096a6497745975f89
    eu-west-3:
      ImageId: ami-0346672391424d8e5
    sa-east-1:
      #ImageId: ami-048837a0bfc1ba1a6
      ImageId: ami-098b893bcc691f3bd
    us-east-1:
      #ImageId: ami-063585f0e06d22308
      #ImageId: ami-098b893bcc691f3bd
      # ubuntu 18
      #ImageId: ami-072519eedc1730252
      #amazon linux
      ImageId: ami-06b7e61d95c2e9cc8
    us-east-2:
      #ImageId: ami-01bd6a1621a6968d7
      #ImageId: ami-09f77b37a0d32243a
      #amazon linux
      ImageId: ami-04f99155cdcd8fb98
    us-west-1:
      #ImageId: ami-05fbe06ba1b862ef6
      #ImageId: ami-0fe05354c2b605fe4
      #amazon linux
      ImageId: ami-0a8c59d72e15fd3fd
    us-west-2:
      #ImageId: ami-0bc87a16c757a7f07
      ImageId: ami-084f81625fbc98fa4

  SpotPriceMap:
    g4dn.xlarge:
      MaxPrice: 0.16
    g4dn.2xlarge:
      MaxPrice: 0.23
    g4dn.12xlarge:
      MaxPrice: 1.57
    p3.2xlarge:
      MaxPrice: 0.92
    p3.8xlarge:
      MaxPrice: 3.68
    p3.16xlarge:
      MaxPrice: 7.36

Resources:

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        InstanceType: !Ref InstanceType
        KeyName:
          Ref: KeyName
        ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", ImageId ]
        SecurityGroupIds:
          - !Ref SecurityGroup
        UserData:
          'Fn::Base64':
            'Fn::Sub': |
              #!/bin/bash -x

              mkdir /crypto
              cd /crypto

              wget https://github.com/trexminer/T-Rex/releases/download/0.19.11/t-rex-0.19.11-linux-cuda11.1.tar.gz
              mkdir t-rex
              (cd t-rex && tar xvfz ../t-rex-0.19.11-linux-cuda11.1.tar.gz)

              wget https://github.com/develsoftware/GMinerRelease/releases/download/2.45/gminer_2_45_linux64.tar.xz
              mkdir gminer
              (cd gminer && tar xvf ../gminer_2_45_linux64.tar.xz)

              # this apparently gets overwritten.. uh!!!
              #cat > /etc/rc.local << __EOF__
              #cd /crypto/bin
              #nohup ./runner.sh &
              #__EOF__
              #chmod +x /etc/rc.local

              INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
              INSTANCE_ID=AWS-ETH-WORKER

              cd /crypto
              wget -O ethminer.tar.gz https://github.com/ethereum-mining/ethminer/releases/download/v0.18.0/ethminer-0.18.0-cuda-9-linux-x86_64.tar.gz
              tar xvfz ethminer.tar.gz
              cd bin

              echo "starting" > /crypto/ethminer.log

              cat > runner.sh << __EOF__
              #!/bin/bash -x
              #SERVERS=(us1 us2 eu1 asia1)
              SERVERS=(us1 us2)

              # when using amazon linux
              export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.trust.crt

              while (true); do
                PREFERRED_SERVER=\${!SERVERS[\${!RANDOM} % \${!#SERVERS[@]}]}
                #./ethminer \
                #  -P stratums://${EthWallet}.${!INSTANCE_ID}@\${!PREFERRED_SERVER}.ethermine.org:5555 \
                #  -P stratums://${EthWallet}.${!INSTANCE_ID}@us1.ethermine.org:5555 \
                #  -P stratums://${EthWallet}.${!INSTANCE_ID}@us2.ethermine.org:5555 \
                #  -P stratums://${EthWallet}.${!INSTANCE_ID}@eu1.ethermine.org:5555 \
                #  -P stratums://${EthWallet}.${!INSTANCE_ID}@asia1.ethermine.org:5555 \
                # >> /crypto/ethminer.log 2>&1

                case ${Miner} in
                  betterhasheth)
                    echo -n "betterhasheth"
                    cd /crypto/bin
                    ./ethminer \
                      -P stratum://${Worker}:${Password}@${Url1} \
                      -P stratum://${Worker}:${Password}@${Url2} \
                      > /crypto/ethminer.log 2>&1
                    ;;

                  ethermineeth)
                    echo -n "ethermineeth"
                    cd /crypto/bin
                    ./ethminer \
                      -P stratums://${EthWallet}@us2.ethermine.org:5555 \
                      -P stratums://${EthWallet}@us1.ethermine.org:5555 \
                      > /crypto/ethminer.log 2>&1
                    ;;

                  twominerseth)
                    echo -n "2miners"
                    cd /crypto/gminer
                    ./miner --algo ethash --server eth.2miners.com:2020 --user ${EthWallet} --pass x \
                       >> /crypto/ethminer.log 2>&1
                    ;;

                  twominersravencoin)
                    echo -n "2miners"
                    cd /crypto/gminer
                    ./miner --algo kawpow --server us-rvn.2miners.com:6060 --user RMRurzYnCYygGHuRygKKMwcuVbMV4emWBW --pass x \
                       >> /crypto/ethminer.log 2>&1
                    ;;

                  *)
                    echo "dunno what kind of miner to use"
                    sleep 60000
                    ;;
                esac
              done
              __EOF__
              chmod +x runner.sh
              nohup ./runner.sh &

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref AWS::StackName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp:
            Ref: SSHAccessIP
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      # As long as you have a default VPC, don't have to specify: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-vpcid
      VpcId:
        Ref: VpcId

  MinerAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 0
      MaxSize: !Ref InstanceCount
      DesiredCapacity: !Ref InstanceCount
      CapacityRebalance: false
      VPCZoneIdentifier: !Ref SubnetIds
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      TerminationPolicies:
        - ClosestToNextInstanceHour
      NotificationConfigurations:
        - TopicARN: !Ref NotificationTopic
          NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
          PropagateAtLaunch: true

  NotificationTopic:
    Type: AWS::SNS::Topic

Outputs:
  NotificationTopic:
    Description: Monitoring notification topic
    Value: !Ref NotificationTopic

  DashboardUrl:
    Description: Ethermine Dashboard URL
    Value: !Sub "https://ethermine.org/miners/${EthWallet}/dashboard"
